version: 0.0
os: linux
files:
  - source: /
    destination: /opt/my_application
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/start_application.sh
      runas: root
  ApplicationStart:
    - location: scripts/run_tests.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root